GET http://localhost:8080/api/posts

###

GET http://localhost:8080/api/posts/2

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 0,
  "content": "Last Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 2,
  "content": "Replace Post"
}

###

POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "id": 150,
  "content": "New ID Post"
}

###

DELETE http://localhost:8080/api/posts/1
